name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    name: Java 21 build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven on JDK 21
        run: mvn --batch-mode --update-snapshots verify